### PR TITLE
Add n2c2_2006 dataset loader

### PR DESCRIPTION
**Pull request by bwang482**
Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

If the following information is NOT present in the issue, please populate:

- **Name:** n2c2_2006
- **Description:** n2c2 2006 smoking status identification task
- **Paper:** [*link to the dataset paper*](https://doi.org/10.1197/jamia.M2408)
- **Data:** [*link to the online home of the dataset*](https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/)

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

**unit-test output**
```
(bigscience-biomedical) bo@macbook biomedical % python -m tests.test_bigbio biodatasets/n2c2_2006/n2c2_2006.py --data_dir /Users/bo/Downloads
INFO:__main__:args: Namespace(path='biodatasets/n2c2_2006/n2c2_2006.py', schema=None, subset_id=None, data_dir='/Users/bo/Downloads', use_auth_token=None)
INFO:__main__:self.PATH: biodatasets/n2c2_2006/n2c2_2006.py
INFO:__main__:self.SUBSET_ID: n2c2_2006
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: /Users/bo/Downloads
INFO:__main__:Checking for _SUPPORTED_TASKS ...
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.TEXT_CLASSIFICATION: 'TXTCLASS'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'TEXT'}
INFO:__main__:schemas_to_check: {'TEXT'}
INFO:__main__:Checking load_dataset with config name n2c2_2006_source
WARNING:datasets.builder:Using custom data configuration n2c2_2006_source-6eec24607a8c4df9
Downloading and preparing dataset n2_c22006_smoking_dataset/n2c2_2006_source to /Users/bo/.cache/huggingface/datasets/n2_c22006_smoking_dataset/n2c2_2006_source-6eec24607a8c4df9/1.0.0/3f8bbd5ed10b5b56e6c79149346725cab9819d27a872c20f0e5d94a0f3dbc79c...
Dataset n2_c22006_smoking_dataset downloaded and prepared to /Users/bo/.cache/huggingface/datasets/n2_c22006_smoking_dataset/n2c2_2006_source-6eec24607a8c4df9/1.0.0/3f8bbd5ed10b5b56e6c79149346725cab9819d27a872c20f0e5d94a0f3dbc79c. Subsequent calls will reuse this data.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 858.35it/s]
INFO:__main__:Checking load_dataset with config name n2c2_2006_bigbio_text
WARNING:datasets.builder:Using custom data configuration n2c2_2006_bigbio_text-6eec24607a8c4df9
Downloading and preparing dataset n2_c22006_smoking_dataset/n2c2_2006_bigbio_text to /Users/bo/.cache/huggingface/datasets/n2_c22006_smoking_dataset/n2c2_2006_bigbio_text-6eec24607a8c4df9/1.0.0/3f8bbd5ed10b5b56e6c79149346725cab9819d27a872c20f0e5d94a0f3dbc79c...
Dataset n2_c22006_smoking_dataset downloaded and prepared to /Users/bo/.cache/huggingface/datasets/n2_c22006_smoking_dataset/n2c2_2006_bigbio_text-6eec24607a8c4df9/1.0.0/3f8bbd5ed10b5b56e6c79149346725cab9819d27a872c20f0e5d94a0f3dbc79c. Subsequent calls will reuse this data.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1010.68it/s]
INFO:__main__:Checking global ID uniqueness
INFO:__main__:Found 104 unique IDs
INFO:__main__:Gathering schema statistics
INFO:__main__:Gathering schema statistics
train
==========
id: 398
document_id: 398
text: 398
labels: 398

test
==========
id: 104
document_id: 104
text: 104
labels: 104

.
----------------------------------------------------------------------
Ran 1 test in 0.567s

OK
```

### CODE REVIEW

**Comment by galtay** [comment]
thanks for this bwang482 ...  hmmm, looks like someone claimed this dataset through the hackathon procedure about 9 days ago ( #219 ) for now, lets make sure the work is shared so it can help other participants. We will make sure everyone who contrinbuted gets some credit.

**Comment by bwang482** [comment]
Ok thanks @galtay ! Here is the ref https://github.com/bigscience-workshop/biomedical/issues/31 if needed.

**Comment by galtay** [comment]
closes #31

**Comment by bwang482** [comment]
Actually @galtay, although these are from the same challenge they are two different tasks and use different datasets.

**Comment by galtay** [comment]
> Actually @galtay, although these are from the same challenge they are two different tasks and use different datasets.

I might be totally confused but I'm seeing two datasets in this PR, 
* n2c2_2006
* n2c2_2008

and one dataset here (https://github.com/bigscience-workshop/biomedical/pull/425)
* n2c2_2008

we are trying to have a 1-1 correspondence between issues and PRs but if its more convenient for you, we can keep both here and close #425

**Pull request closed without merging**
