### PR TITLE
Closes #236 : SciCo

### LINKED ISSUE #236: Create dataset loader for SciCo
## Adding a Dataset
- **Name:** SciCo
- **Description:** Hierarchical cross-document coreference resolution
- **Task:** COREF
- **Paper:** https://www.akbc.ws/2021/assets/pdfs/OFLbgUP04nC.pdf
- **Data:** https://scico.apps.allenai.org/
- **License:** Apache License 2.0

### PR DESCRIPTION
**Pull request by karthikrangasai**
Closes #236 

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by hakunanatasha** [comment]
@jason-fries

**Comment by mariosaenger** [comment]
@phlobo This dataset doesn't contain biomedical. See:

https://huggingface.co/datasets/allenai/scico/viewer/default/train?p=1

I would recommend to close the PR.

**Comment by phlobo** [comment]
@mariosaenger agreed! It's a bit off-topic, although a very interesting dataset.

**Comment by mariosaenger** [comment]
We'll close the PR since the dataset is out-of-focus of BigBio.

**Pull request closed without merging**
