### PR TITLE
Closes #228

### LINKED ISSUE #228: Create dataset loader for MEDIQA 2019 QA
## Adding a Dataset
- **Name:** MEDIQA 2019 QA
- **Description:** *None provided*
- **Task:** QA
- **Paper:** https://www.aclweb.org/anthology/W19-5039/
- **Data:** https://github.com/abachaa/MEDIQA2019/tree/master/MEDIQA_Task3_QA
- **License:** ?

### PR DESCRIPTION
**Pull request by SamuelCahyawijaya**
Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

If the following information is NOT present in the issue, please populate:

- **Name:** MEDIQA 2019 QA
- **Description:** https://sites.google.com/view/mediqa2019
- **Paper:** https://aclanthology.org/W19-5039/
- **Data:** https://github.com/abachaa/MEDIQA2019

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.

### CODE REVIEW

**Review by hakunanatasha — CHANGES_REQUESTED** [review]
Hi @SamuelCahyawijaya the PR history only shows me some jpgs from the README - are you sure you committed the right files?

**Comment by SamuelCahyawijaya** [comment]
Oh sorry, my mistake, I just commit the code and remove the unnecessary files.

**Review by ruisi-su — APPROVED** [review]
confirmed load_dataset() and unit-tests passed

**Comment by hakunanatasha** [comment]
@SamuelCahyawijaya same issue as before - accepting the PR unfortunately deletes the images but i'll fix it after the merge.

**Review by hakunanatasha — APPROVED** [review]

**Pull request merged**
