### PR TITLE
Closes #61 [DEPRECATED]

### LINKED ISSUE #61: Create a dataset loader for SPL-ADR-200db - Adverse Drug Reactions
From https://bionlp.nlm.nih.gov/tac2017adversereactions/

### PR DESCRIPTION
**Pull request by MFreidank**
Closes issue #61 

Relevant details:

- **Name:** *SPL ADR 200 DB*
- **Description:** *SPL ADR 200 DB is a dataset for adverse event mentions annotated at entity level in Structured Product Labels of 200 FDA-approved drugs. Annotations were done as part of a partnership between
the United States Food and Drug Administration (FDA) and the National Library of Medicine.
These data were used for the adverse event challenge of TAC (Text Analysis Conference) 2017, see also:
https://bionlp.nlm.nih.gov/tac2017adversereactions/*
- **Paper:** *https://www.researchgate.net/publication/322810855_A_dataset_of_200_structured_product_labels_annotated_for_adverse_drug_reactions*
- **Data:** *https://bionlp.nlm.nih.gov/tac2017adversereactions/*

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

Please let me know in case any changes are required. Looking forward to your comments!

### CODE REVIEW

**Review by WojciechKusa — COMMENTED** [review]
Hi @MFreidank. The code looks great, thank you for your contribution! :tada:

I have noticed that [ADR dataset](https://bionlp.nlm.nih.gov/tac2017adversereactions/) also contains unannotated test [data split](https://bionlp.nlm.nih.gov/tac2017adversereactions/unannotated_xml.tar.gz).

If the schema is similar to the trainset, it would be nice to add it to the loader as data in a split called "unannotated". What do you think?

**Comment by WojciechKusa** [comment]
Thanks for the quick reply @MFreidank.

I would vote for option (2) and allow for failing unittest in _unannotated_ split as we might relax this requirement after the hackathon. Alternatively, I would only implement the _unannotated_ schema for `source` (option 1).

  However, it would be great to get a second opinion @galtay @hakunanatasha?

**Comment by WojciechKusa** [comment]
Hi @MFreidank,
We have a [fix](https://github.com/bigscience-workshop/biomedical/pull/398) coming to the unit-tests that will allow for bypassing specific arguments. This will help with the case of empty entities. 

So we agreed that the best way would be to go with option (2) and, for the moment, let `bigbio_unannotated` fail:

> Implement a source and bigbio subset for train and unannotated respectively and accept that the test for bigbio_unannotated will fail.

Please let us know if you have time to implement this :)

**Comment by MFreidank** [comment]
Hi @WojciechKusa 
Thank you for this update!

I'll get to working on the changes to implement option (2) right away.

**Comment by WojciechKusa** [comment]
Thanks @MFreidank, looks good to me, I am happy to merge it!

I agree, let's open a new PR just to make sure that we commit only this dataset.

**Comment by MFreidank** [comment]
Okay, closing this PR and re-opening a separate one with only this dataset. 
Will tag you directly when it is open so we can proceed to merging @WojciechKusa

**Pull request closed without merging**
