### PR TITLE
Closes #429

### LINKED ISSUE #429: Create dataset loader for BioRED
## Adding a Dataset
- **Name:** *BioRED*
- **Description:** * RE corpus with multiple entity types (e.g., gene/protein, disease, chemical) and relation pairs (e.g., gene-disease; chemical-chemical), on a set of 600 PubMed articles*
- **Task:** *NER, RE*
- **Paper:** *[link to the dataset paper](https://arxiv.org/abs/2204.04263)*
- **Data:** *[link to the Github repository or current dataset location](https://ftp.ncbi.nlm.nih.gov/pub/lu/BioRED/)*
- **License:** *NA*
- **Motivation:** *multiple entity types (e.g., gene/protein, disease, chemical)*

### PR DESCRIPTION
**Pull request by shamikbose**
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

**Note**: I am able to load the dataset with `load_dataset()` with both schemas without any issues and the dataloader passes all tests. However, I have a number of warnings that look like this

```WARNING:__main__:Referenced element ('286934', 'entity') could not be found in existing ids {('4957', 'entity'), ('4941', 'entity'), ('4959', 'entity'), ('4962', 'entity'), ('4948', 'entity'), ('4954', 'entity'), ('4968', 'entity'), ('4963', 'entity'), ('4938', 'entity'), ('4947', 'entity'), ('4958', 'entity'), ('4951', 'entity'), ('4971', 'entity'), ('4936', 'entity'), ('4946', 'entity'), ('4943', 'entity'), ('4969', 'entity'), ('4967', 'entity'), ('4952', 'entity'), ('4939', 'entity'), ('4944', 'entity'), ('4950', 'entity'), ('4956', 'entity'), ('4964', 'entity'), ('4953', 'entity'), ('4955', 'entity'), ('4974', 'entity'), ('4937', 'entity'), ('4949', 'entity'), ('4972', 'entity'), ('4942', 'entity'), ('4975', 'entity'), ('4935', 'entity'), ('4960', 'entity'), ('4970', 'entity'), ('4965', 'entity'), ('4945', 'entity'), ('4966', 'entity'), ('4973', 'entity'), ('4961', 'entity'), ('4934', 'entity'), ('4940', 'entity')}. Please make sure that this is not because of a bug in your data loader.```

I'm unable to resolve these warnings, so any help is much appreciated

### CODE REVIEW

**Comment by shamikbose** [comment]
@sg-wbi @galtay Can I have some clarity on this warning please?

**Comment by sg-wbi** [comment]
Hey @shamikbose ! This is `RELATION_EXTRACTION` dataset which has `relations` which are in the form:
```
    {
        "id": "100",
        "type": "chemical-induced disease",
        "arg1_id": "10",
        "arg2_id": "32",
        "normalized": []
    }
```
The values of `arg1_id` and `arg2_id` must be an `id` of an `entity` and the warning is telling you that a relation is referencing (i.e. having `arg1_id` or `arg2_id`) the entity with id `286934` but it could not find the entity with this `id`.

We saw this issue already with a couple of `EVENT_EXTRACTION` datasets. It is possible that one relation is referencing another relation which at the moment is not allowed. [See what we do here](https://github.com/bigscience-workshop/biomedical/blob/master/bigbio/utils/parsing.py#L367) with brat parsing as an example of workaround.

**Comment by shamikbose** [comment]
> Hey @shamikbose ! This is `RELATION_EXTRACTION` dataset which has `relations` which are in the form:
> 
> ```
>     {
>         "id": "100",
>         "type": "chemical-induced disease",
>         "arg1_id": "10",
>         "arg2_id": "32",
>         "normalized": []
>     }
> ```
> 
> The values of `arg1_id` and `arg2_id` must be an `id` of an `entity` and the warning is telling you that a relation is referencing (i.e. having `arg1_id` or `arg2_id`) the entity with id `286934` but it could not find the entity with this `id`.
> 
> We saw this issue already with a couple of `EVENT_EXTRACTION` datasets. It is possible that one relation is referencing another relation which at the moment is not allowed. [See what we do here](https://github.com/bigscience-workshop/biomedical/blob/master/bigbio/utils/parsing.py#L367) with brat parsing as an example of workaround.

Thanks for the explanation and the link, @sg-wbi ! I'll try and figure out how to work around this situation in this case

**Comment by shamikbose** [comment]
> Hey @shamikbose ! This is `RELATION_EXTRACTION` dataset which has `relations` which are in the form:
> 
> ```
>     {
>         "id": "100",
>         "type": "chemical-induced disease",
>         "arg1_id": "10",
>         "arg2_id": "32",
>         "normalized": []
>     }
> ```
> 
> The values of `arg1_id` and `arg2_id` must be an `id` of an `entity` and the warning is telling you that a relation is referencing (i.e. having `arg1_id` or `arg2_id`) the entity with id `286934` but it could not find the entity with this `id`.
> 
Since this is a NER and an RE dataset, how would I generate unqiue IDs for entities? The same entity can exist in the document twice
```
8829135	0	11	Nefiracetam	ChemicalEntity	C058876
8829135	13	20	DM-9384	ChemicalEntity	C058876
8829135	31	42	apomorphine	ChemicalEntity	D001058
8829135	51	58	amnesia	DiseaseOrPhenotypicFeature	D000647
.
.
.
8829135	Negative_Correlation	C058876	D001058	Novel
8829135	Negative_Correlation	C058876	D000647	Novel
```

In this case above, C058876 exists in the same document twice and has relations with different concepts in the same document. If I try to make ids with the document_id prefix, they will not be unique. Any help is appreciated here :)

**Comment by shamikbose** [comment]
@sg-wbi I figured out what was happening. A number of mentions in the document had multiple concept_ids that were comma-separated as shown below:

`19881468	1386	1423	squamous- and small-cell lung cancers	DiseaseOrPhenotypicFeature	D002289,D055752`

This has been handled in the latest commit. The latest push passes all tests and can be loaded with `load_dataset()` . Thanks for the help! :)

**Review by ruisi-su — APPROVED** [review]
thanks for tackling this dataset @shamikbose! It is passing the unit test and can be loaded via `load_dataset`.

**Pull request merged**
