### PR TITLE
Closes #419

### LINKED ISSUE #419: Proposal to add the CAS dataset
## Adding a Dataset
- **Name:** *CAS: French Corpus with Clinical Cases*
- **Description:** *The CAS corpus is build on clinical cases, such as they are reported in the published scientific literature in French. The corpus contain over 397,000 word occurrences, and the existing linguistic and semantic annotations.*
- **Task:** *POS-Tagging & Lemmatization*
- **Paper:** *https://aclanthology.org/W18-5614/*
- **Data:** *http://natalia.grabar.free.fr/resources.php*
- **License:** *Unknown*
- **Motivation:** *This is the only POS-Tagging corpus for clinical cases in french.*

### PR DESCRIPTION
**Pull request by giganttheo**
### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

Unit tests : 

```
INFO:__main__:args: Namespace(data_dir='/content/biomedical/biodatasets/cas', path='biodatasets/cas/cas.py', schema=None, subset_id=None, use_auth_token=None)
INFO:__main__:self.PATH: biodatasets/cas/cas.py
INFO:__main__:self.SUBSET_ID: cas
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: /content/biomedical/biodatasets/cas
INFO:__main__:Checking for _SUPPORTED_TASKS ...
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.TEXT_CLASSIFICATION: 'TXTCLASS'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'TEXT'}
INFO:__main__:schemas_to_check: {'TEXT'}
INFO:__main__:Checking load_dataset with config name cas_source
WARNING:datasets.builder:Using custom data configuration cas_source-7bf61d9023e5f3b1
Downloading and preparing dataset cas/cas_source to /root/.cache/huggingface/datasets/cas/cas_source-7bf61d9023e5f3b1/1.0.0/6352bc1da2d987267c298b7057acaef20887cb693e8b138a4751857e49514cd3...
Dataset cas downloaded and prepared to /root/.cache/huggingface/datasets/cas/cas_source-7bf61d9023e5f3b1/1.0.0/6352bc1da2d987267c298b7057acaef20887cb693e8b138a4751857e49514cd3. Subsequent calls will reuse this data.
100% 1/1 [00:00<00:00, 599.96it/s]
INFO:__main__:Checking load_dataset with config name cas_bigbio_text
WARNING:datasets.builder:Using custom data configuration cas_bigbio_text-7bf61d9023e5f3b1
WARNING:datasets.builder:Reusing dataset cas (/root/.cache/huggingface/datasets/cas/cas_bigbio_text-7bf61d9023e5f3b1/1.0.0/6352bc1da2d987267c298b7057acaef20887cb693e8b138a4751857e49514cd3)
100% 1/1 [00:00<00:00, 710.42it/s]
INFO:__main__:Checking global ID uniqueness
INFO:__main__:Found 7580 unique IDs
INFO:__main__:Gathering schema statistics
INFO:__main__:Gathering schema statistics
train
==========
id: 7580
document_id: 7580
text: 7580
labels: 7580

.
----------------------------------------------------------------------
Ran 1 test in 4.361s

OK
```

Note : This data loading script is very similar as the one for closing #69  ( PR : #379 ) as both datasets are in the same format as given by Clément Dalloux (one of the authors of CAS) in his download link ( http://clementdalloux.fr/?page_id=28 )

### CODE REVIEW

**Comment by sunnnymskang** [comment]
@giganttheo The link provided for the dataset is not accessible - Can you provide the alternative links for the dataset?

**Comment by giganttheo** [comment]
> @giganttheo The link provided for the dataset is not accessible - Can you provide the alternative links for the dataset?

Yes, I should have precised that this dataset is local. The link is for the form to request access to the files. The zip file is sent by email and contains files for both ESSAI and CAS dataset

**Comment by sunnnymskang** [comment]
@giganttheo  Thank you for getting back to me! The form for getting the dataset isn't working and it'd be awesome if I can get the sample set of dataset and test them locally. If this is not possible, let me know - Since you've already implemented the similar dataset previously, alternatively I can focus on checking the formatting

**Comment by jason-fries** [comment]
Hey @sunnnymskang 
Have you had a chance to double check this file?

**Comment by sunnnymskang** [comment]
@jason-fries Sorry for the delay! I've just received the dataset via email and checking it rn

**Comment by sunnnymskang** [comment]
@giganttheo My bad! I was looking at the wrong link! Thank you for providing more detail - I'll review rn

**Comment by sunnnymskang** [comment]
Unit tests pass and the inspection on loaded dataset looks good to me

**Review by sunnnymskang — APPROVED** [review]
Unit tests pass and the inspection on loaded dataset looks good to me

**Pull request merged**
