### PR TITLE
Create dataset loader for NLPMedTerm (CT-EBM-SP) corpus

### LINKED ISSUE #283: Add dataset loader for NLPMedTerm corpus
## Adding a Dataset
- **Name:** *NLPMedTerm*
- **Description:** *A  Spanish clinical trials corpus annotated with UMLS entities*
- **Task:** *NER,NEN*
- **Paper:** *http://www.lllf.uam.es/ESP/nlpdata/wp2/s12911-021-01395-z.pdf*
- **Data:** *http://www.lllf.uam.es/ESP/nlpdata/wp2/CT-EBM-SP.zip*
- **License:** *CC BY-NC 4.0*
- **Motivation:** *Non-english clinical trails corpora are very rare*

### PR DESCRIPTION
**Pull request by danilexn**
Closes #283

### Checkbox
**This is done using `datasets` format**
- [x] Create the dataset script `/datasets/my_dataset/my_dataset.py` using the template
- [x] Fill the `_DESCRIPTION` and `_CITATION` variables
- [x] Implement `_infos()`, `_split_generators()` and `_generate_examples()` in dataloader script
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is filled with the different configurations of the dataset and that the `BUILDER_CONFIG_CLASS` is specified if there is a custom config class.
- [x] Code works with `datasets`
- [x] Passes all unit-tests for appropriate schema and keys

### CODE REVIEW

**Review by galtay — APPROVED** [review]
looks good, thank you!

**Comment by galtay** [comment]
note for other reviewers and future participants, tests can be run on the subsets using, 
```
python -m tests.test_bigbio biodatasets/ctebmsp/ctebmsp.py --subset_id ctebmspabstracts
python -m tests.test_bigbio biodatasets/ctebmsp/ctebmsp.py --subset_id ctebmspeudract
```

**Comment by galtay** [comment]
sorry to change the approval, but can you implement the subset_ids with underscores here as in https://github.com/bigscience-workshop/biomedical/pull/319 ... this would make them (`ctebmsp_abstracts` and `ctebmsp_eudract`)

**Review by galtay — CHANGES_REQUESTED** [review]
updating to "request changes" for easier tracking in PR list

**Comment by danilexn** [comment]
> updating to "request changes" for easier tracking in PR list

Done! Thank you very much for the suggestion

**Comment by danilexn** [comment]
> thanks for the subset changes!

My pleasure! :hugs:

**Pull request merged**
