### PR TITLE
Closes #67 - Add Monero

### LINKED ISSUE #67: Create a dataset loader for MoNERo
From https://www.racai.ro/en/tools/text/

### PR DESCRIPTION
**Pull request by napsternxg**
Fixes #67 - Add Monero

If the following information is NOT present in the issue, please populate:

- **Name:** *MoNERo*
- **Description:** *MoNERo: a Biomedical Gold Standard Corpus for the Romanian Language for part of speech tagging and named entity recognition.*
- **Paper:** *https://www.racai.ro/en/tools/text/*
- **Data:** *https://github.com/bigscience-workshop/biomedical/files/8550757/MoNERo.tar.gz*

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by hakunanatasha** [comment]
@napsternxg passes all the unit tests and loads fine, but I noticed if I do the following:
```
from datasets import load_dataset
x = load_dataset("biodatasets/monero/monero.py", name="monero_bigbio_kb")["train"]["entities"][-1]
```
I find these all empty. Is this intended?

**Comment by hakunanatasha** [comment]
@napsternxg also I made a small change at the end of the file (near the main call)

**Comment by napsternxg** [comment]
Hi @hakunanatasha thanks. Let me have a look at this. I will address this by early next week.

**Comment by napsternxg** [comment]
Hi @hakunanatasha I checked the entities. They are present. When no entity is present in a doc we see an empty list. 
This is a better way to check:

```python
from datasets import load_dataset
data = load_dataset("biodatasets/monero/monero.py", name="monero_bigbio_kb")
data["train"]["entities"][-5:]
```
Will output

```
[[],
 [],
 [],
 [{'id': 'docid-4982-E0',
   'type': 'DISO',
   'text': ['hemipareză spastică'],
   'offsets': [[109, 128]],
   'normalized': []}],
 []]
```

This means only the second last doc among the last 5 docs has any entity. 

I also added a fix about entity offsets. 
I think this PR is ready for Merge.

**Comment by mariosaenger** [comment]
@phlobo I revised this dataset. Please have a look at it.

**Review by phlobo — APPROVED** [review]
LGTM!

**Pull request merged**
