### PR TITLE
Closes #220

### LINKED ISSUE #220: Create dataset loader for n2c2 2014 - Deidentification & Heart Disease
## Adding a Dataset
- **Name:** n2c2 2014 - Deidentification & Heart Disease
- **Description:** *None provided*
- **Task:** NER,DOC_CLASS
- **Paper:** https://pubmed.ncbi.nlm.nih.gov/26225918/
- **Data:** https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/
- **License:** DUA-C/NC

### PR DESCRIPTION
**Pull request by jdposada**
Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

If the following information is NOT present in the issue, please populate:

- **Name:** *name of the dataset*
- **Description:** *short description of the dataset (or link to social media or blog post)*
- **Paper:** *link to the dataset paper if available*
- **Data:** *link to the online home of the dataset*

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

```shell
INFO:__main__:args: Namespace(dataloader_path='bigbio/biodatasets/n2c2_2014_deid/n2c2_2014_deid.py', data_dir='/workspaces/biomedical/biodatasets/n2c2_2014/tar_gz', config_name=None, bypass_splits=[], bypass_keys=[], bypass_split_key_pairs=[])
INFO:__main__:all_config_names: ['n2c2_2014_source', 'n2c2_2014_bigbio_kb']
INFO:__main__:self.PATH: bigbio/biodatasets/n2c2_2014_deid/n2c2_2014_deid.py
INFO:__main__:self.NAME: n2c2_2014_source
INFO:__main__:self.DATA_DIR: /workspaces/biomedical/biodatasets/n2c2_2014/tar_gz
INFO:__main__:importing module .... 
INFO:__main__:imported module <module 'bigbio.biodatasets.n2c2_2014_deid.n2c2_2014_deid' from '/workspaces/biomedical/bigbio/biodatasets/n2c2_2014_deid/n2c2_2014_deid.py'>
INFO:__main__:Checking for _SUPPORTED_TASKS ...
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.NAMED_ENTITY_RECOGNITION: 'NER'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'KB'}
INFO:__main__:Checking load_dataset with config name n2c2_2014_source
WARNING:datasets.builder:Using custom data configuration n2c2_2014_source-57e9df040ed9f011
WARNING:datasets.builder:Reusing dataset n2_c22014_deid_dataset (/home/jovyan/.cache/huggingface/datasets/n2_c22014_deid_dataset/n2c2_2014_source-57e9df040ed9f011/1.0.0/f1723087f9fabf88ed456e88f4ec257db3cbcfa354e024e3672d9df6712b5efc)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 331.51it/s]
INFO:__main__:schema = source
.
----------------------------------------------------------------------
Ran 1 test in 0.183s

OK
INFO:__main__:self.PATH: bigbio/biodatasets/n2c2_2014_deid/n2c2_2014_deid.py
INFO:__main__:self.NAME: n2c2_2014_bigbio_kb
INFO:__main__:self.DATA_DIR: /workspaces/biomedical/biodatasets/n2c2_2014/tar_gz
INFO:__main__:importing module .... 
INFO:__main__:imported module <module 'bigbio.biodatasets.n2c2_2014_deid.n2c2_2014_deid' from '/workspaces/biomedical/bigbio/biodatasets/n2c2_2014_deid/n2c2_2014_deid.py'>
INFO:__main__:Checking for _SUPPORTED_TASKS ...
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.NAMED_ENTITY_RECOGNITION: 'NER'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'KB'}
INFO:__main__:Checking load_dataset with config name n2c2_2014_bigbio_kb
WARNING:datasets.builder:Using custom data configuration n2c2_2014_bigbio_kb-57e9df040ed9f011
WARNING:datasets.builder:Reusing dataset n2_c22014_deid_dataset (/home/jovyan/.cache/huggingface/datasets/n2_c22014_deid_dataset/n2c2_2014_bigbio_kb-57e9df040ed9f011/1.0.0/f1723087f9fabf88ed456e88f4ec257db3cbcfa354e024e3672d9df6712b5efc)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 203.62it/s]
INFO:__main__:schema = KB
INFO:__main__:Checking global ID uniqueness
INFO:__main__:Found 12490 unique IDs
INFO:__main__:Gathering dataset statistics
train
==========
id: 790
document_id: 790
passages: 790
entities: 17405
normalized: 0
events: 0
coreferences: 0
relations: 0

test
==========
id: 514
document_id: 514
passages: 514
entities: 11462
normalized: 0
events: 0
coreferences: 0
relations: 0

INFO:__main__:Testing schema for: train
INFO:__main__:Testing schema for: test
INFO:__main__:Checking if referenced IDs are properly mapped
INFO:__main__:KB ONLY: Checking passage offsets
INFO:__main__:KB ONLY: Checking entity offsets
WARNING:__main__:Example:1898 - entity:1917  text:`October 31,  2086` != text_by_offset:`October 31,

<hidden output>

There are features with wrong offsets! This is not a hard failure, as it is common for this type of datasets. However, if the error list is long (e.g. >10) you should double check your code. 


INFO:__main__:KB ONLY: multi-label `db_id`
INFO:__main__:KB ONLY: Checking event offsets
INFO:__main__:KB ONLY: Checking coref offsets
INFO:__main__:KB ONLY: multi-label `type` fields
.
----------------------------------------------------------------------
Ran 1 test in 11.500s

OK
```

### CODE REVIEW

**Comment by jdposada** [comment]
Closes https://github.com/bigscience-workshop/biomedical/issues/220

**Comment by ruisi-su** [comment]
hi @jdposada, thank you for helping with this dataset! Unit tests are running with the below warnings, could you check if these can be resolved? Tagging the unit-testing admins @galtay @hakunanatasha @sg-wbi.
```WARNING:__main__:Example:1898 - entity:1917  text:`October 31,  2086` != text_by_offset:`October 31,

2086`
Example:1898 - entity:1918  text:`February  2086` != text_by_offset:`February

2086`
Example:8100 - entity:8114  text:`Yehuda   Landers` != text_by_offset:`Yehuda

Landers`
Example:8100 - entity:8121  text:`Michael   Ogrady` != text_by_offset:`Michael

Ogrady`
Example:10950 - entity:10968  text:`February of 2073` != text_by_offset:`February
of 2073`
Example:14087 - entity:14102  text:`Harold Nutter` != text_by_offset:`Harold
Nutter`
Example:14380 - entity:14394  text:`Quiana N.   Bullock` != text_by_offset:`Quiana N.

Bullock`
Example:15705 - entity:15718  text:`Vicki Klein` != text_by_offset:`Vicki
Klein`
```

**Comment by jdposada** [comment]
Hi @ruisi-su,

I saw those warnings myself. The errors you mentioned plus others that the unit test show are dataset errors that are not systematic. Short of fixing those "manually" within the loader I believe there is no systematic way of addressing them. I believe the best way to move forward if we would want to avoid those warinings entirely is to discard those labels or the entire report containing them. Let me know how should I proceed. Thanks

**Comment by galtay** [comment]
@jdposada @ruisi-su  can we confirm that the warnings are all for new line style mismatches? 
in this example,
```
Example:15705 - entity:15718  text:`Vicki Klein` != text_by_offset:`Vicki
Klein`
```
the text looks like it would be equal to the text_by_offset with the removal of some new line characters. If most (all) of the warning are like this and not for truncated mentions (i.e. `Vicki Kl`) then I think its OK to merge ... I know several other n2c2 datasets have issues like this.

**Comment by ruisi-su** [comment]
> @jdposada @ruisi-su can we confirm that the warnings are all for new line style mismatches? in this example,
> 
> ```
> Example:15705 - entity:15718  text:`Vicki Klein` != text_by_offset:`Vicki
> Klein`
> ```
> 
> the text looks like it would be equal to the text_by_offset with the removal of some new line characters. If most (all) of the warning are like this and not for truncated mentions (i.e. `Vicki Kl`) then I think its OK to merge ... I know several other n2c2 datasets have issues like this.

Yeah, they were all new lines except one `Example:15942 - entity:15957 text: `Johnson and Johnson` != text_by_offset:`Johnson & Johnson`.

**Review by ruisi-su — APPROVED** [review]
thanks @jdposada for tackling this dataset!

**Pull request merged**
