### PR TITLE
Pin bioc to 2.0.post1

### PR DESCRIPTION
**Pull request by JohnGiorgi**
# Overview

This PR updates `bioc` from `1.3.7` to `2.0.post1` in the `requirements.txt`. This allows the use of the new `pubtator` module of this package for parsing datasets in the PubTator format. See the discussion about this change here: https://github.com/bigscience-workshop/biomedical/pull/370#issuecomment-1092917970.

@sg-wbi mind taking a look?

## TODO

- [x] Is there a way to run all the unit tests? Want to make sure this doesn't break anything

### CODE REVIEW

**Comment by hakunanatasha** [comment]
@sg-wbi @JohnGiorgi do you know if there is any changes that may affect dataloaders using the older version (not all even use bioc though)

**Comment by JohnGiorgi** [comment]
> @sg-wbi @JohnGiorgi do you know if there is any changes that may affect dataloaders using the older version (not all even use bioc though)

Is there a way for me to run all unit tests for all dataloaders? That should give us an idea

**Comment by JohnGiorgi** [comment]
@sg-wbi @hakunanatasha 

Okay, so I found all data loaders that `import bioc`, which was just `bc5cdr.py` and `nlmchem.py`. They needed only small changes to support `bioc>=2.0.0` which I made. I ran the `check_file` and the unit tests and everything looks good.

**Comment by galtay** [comment]
I think we had a few new datasets come in that use `bioc` can we check / update those? ... This is going to be a little bit tricky to orchestrate if we want to update, but I do think its a good idea. Lets try and make sure everything that is checked in works and then we'll have to make an announcement in discord. It's very possible that we'll have to continue to update some as people check in from older environments, but that's OK too.

**Comment by galtay** [comment]
here is what a quick file search shows, 
```
ag "import bioc"
examples/bc5cdr.py
29:import bioc

examples/nlmchem.py
19:import bioc

utils/parsing.py
5:import bioc

biodatasets/nlm_gene/nlm_gene.py
20:import bioc

biodatasets/chemdner/chemdner.py
19:import bioc

biodatasets/bc5cdr/bc5cdr.py
29:import bioc

biodatasets/nlmchem/nlmchem.py
19:import bioc
```

**Comment by galtay** [comment]
@sg-wbi  can we try and get any dataloader script updates that you are aware of into this PR?

**Comment by galtay** [comment]
@sg-wbi @JohnGiorgi @hakunanatasha in the interest of time, I might just make a new PR and put all the changes in ... will start on the changes and see if I can do it quickly :)

**Comment by hakunanatasha** [comment]
@JohnGiorgi apologies - I missed your ping earlier; currently no we haven't written a script that does all dataloaders since some use local packages which will cause the pipeline to break (there is a work around but we haven't had the bandwidth to tidy it up). @galtay is on this though, we will likely merge bioc's updated version ASAP and port all Prs with bioc to the newer version. Thank you for your hard work!

**Comment by galtay** [comment]
closing in favor of #397

**Pull request closed without merging**
