### PR TITLE
Closes #212

### LINKED ISSUE #212: Create dataset loader for GENETAG
## Adding a Dataset
- **Name:** GENETAG
- **Description:** *None provided*
- **Task:** NER
- **Paper:** https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-6-S1-S3
- **Data:** https://github.com/openbiocorpora/genetag
- **License:** Public Domain

### PR DESCRIPTION
**Pull request by s-desh**
Closes #212 
### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.
Ran tests with --subset_id ["genetagcorrect","genetaggold]
#### Unit tests output
```
INFO:__main__:args: Namespace(data_dir=None, path='biodatasets/genetag/genetag.py', schema=None, subset_id='genetaggold', use_auth_token=None)
INFO:__main__:self.PATH: biodatasets/genetag/genetag.py
INFO:__main__:self.SUBSET_ID: genetaggold
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: None
INFO:__main__:Checking for _SUPPORTED_TASKS ...
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.NAMED_ENTITY_RECOGNITION: 'NER'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'KB'}
INFO:__main__:schemas_to_check: {'KB'}
INFO:__main__:Checking load_dataset with config name genetaggold_source
Downloading and preparing dataset genetag_dataset/genetaggold_source to /home/elucidata/.cache/huggingface/datasets/genetag_dataset/genetaggold_source/1.0.0/8b90ee50f7f12169837f641572d33c43a542402983eb07aeb144afee21e4d150...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 2934.45it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 484.83it/s]
Dataset genetag_dataset downloaded and prepared to /home/elucidata/.cache/huggingface/datasets/genetag_dataset/genetaggold_source/1.0.0/8b90ee50f7f12169837f641572d33c43a542402983eb07aeb144afee21e4d150. Subsequent calls will reuse this data.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 628.83it/s]
INFO:__main__:Checking load_dataset with config name genetaggold_bigbio_kb
WARNING:datasets.builder:Reusing dataset genetag_dataset (/home/elucidata/.cache/huggingface/datasets/genetag_dataset/genetaggold_bigbio_kb/1.0.0/8b90ee50f7f12169837f641572d33c43a542402983eb07aeb144afee21e4d150)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 167.96it/s]
INFO:__main__:Checking global ID uniqueness
INFO:__main__:Found 15949 unique IDs
INFO:__main__:Gathering schema statistics
INFO:__main__:Gathering schema statistics
train
==========
id: 7500
document_id: 7500
passages: 7500
entities: 8931
normalized: 0
events: 0
coreferences: 0
relations: 0

test
==========
id: 2500
document_id: 2500
passages: 2500
entities: 2986
events: 0
coreferences: 0
relations: 0
normalized: 0

validation
==========
id: 5000
document_id: 5000
passages: 5000
entities: 5949
normalized: 0
events: 0
coreferences: 0
relations: 0

INFO:__main__:Checking if referenced IDs are properly mapped
INFO:__main__:KB ONLY: Checking passage offsets
INFO:__main__:KB ONLY: Checking entity offsets
INFO:__main__:KB ONLY: Checking event offsets
INFO:__main__:KB ONLY: Checking coref offsets
.
----------------------------------------------------------------------
Ran 1 test in 20.950s

OK
```

```
INFO:__main__:args: Namespace(data_dir=None, path='biodatasets/genetag/genetag.py', schema=None, subset_id='genetagcorrect', use_auth_token=None)
INFO:__main__:self.PATH: biodatasets/genetag/genetag.py
INFO:__main__:self.SUBSET_ID: genetagcorrect
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: None
INFO:__main__:Checking for _SUPPORTED_TASKS ...
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.NAMED_ENTITY_RECOGNITION: 'NER'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'KB'}
INFO:__main__:schemas_to_check: {'KB'}
INFO:__main__:Checking load_dataset with config name genetagcorrect_source
Downloading and preparing dataset genetag_dataset/genetagcorrect_source to /home/elucidata/.cache/huggingface/datasets/genetag_dataset/genetagcorrect_source/1.0.0/8b90ee50f7f12169837f641572d33c43a542402983eb07aeb144afee21e4d150...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 3871.67it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 606.52it/s]
Dataset genetag_dataset downloaded and prepared to /home/elucidata/.cache/huggingface/datasets/genetag_dataset/genetagcorrect_source/1.0.0/8b90ee50f7f12169837f641572d33c43a542402983eb07aeb144afee21e4d150. Subsequent calls will reuse this data.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 672.49it/s]
INFO:__main__:Checking load_dataset with config name genetagcorrect_bigbio_kb
WARNING:datasets.builder:Reusing dataset genetag_dataset (/home/elucidata/.cache/huggingface/datasets/genetag_dataset/genetagcorrect_bigbio_kb/1.0.0/8b90ee50f7f12169837f641572d33c43a542402983eb07aeb144afee21e4d150)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 145.50it/s]
INFO:__main__:Checking global ID uniqueness
INFO:__main__:Found 14275 unique IDs
INFO:__main__:Gathering schema statistics
INFO:__main__:Gathering schema statistics
train
==========
id: 7500
document_id: 7500
passages: 7500
entities: 6588
normalized: 0
events: 0
coreferences: 0
relations: 0

test
==========
id: 2500
document_id: 2500
passages: 2500
entities: 2157
events: 0
coreferences: 0
relations: 0
normalized: 0

validation
==========
id: 5000
document_id: 5000
passages: 5000
entities: 4275
normalized: 0
events: 0
coreferences: 0
relations: 0

INFO:__main__:Checking if referenced IDs are properly mapped
INFO:__main__:KB ONLY: Checking passage offsets
INFO:__main__:KB ONLY: Checking entity offsets
INFO:__main__:KB ONLY: Checking event offsets
INFO:__main__:KB ONLY: Checking coref offsets
.
----------------------------------------------------------------------
Ran 1 test in 19.721s

OK
```

### CODE REVIEW

**Review by sg-wbi — COMMENTED** [review]
@s-desh Thank you for your contribution! You did an incredible work here! 
I have noticed that the dataset contains as well POS-tagged sentences (`TAGGED_GENE_CORPUS`).  Could you please add in the `source` schema this information? This is to preserve as much info as possible from the original dataset (e.g. as it's done [here](https://github.com/giganttheo/biomedical/blob/essai/biodatasets/essai/essai.py#L76))

**Comment by s-desh** [comment]
@sg-wbi Thank you for reviewing the PR.
So, I can add the POS tagged sentences directly as they are mentioned in the source (I believe that is happening [here](https://github.com/giganttheo/biomedical/blob/essai/biodatasets/essai/essai.py#L76)) in a "pos_tags" field for each sentence in `source` schema? 
Example:
```
"pos_tags" : "We/PRP propose/VBP a/DT model/NN in/IN which/WDT..."
```

**Comment by sg-wbi** [comment]
Yes exactly, that would be the idea. And having a `tokenized_sentence` where there is a 1:1 correspondence between token and POS.

**Comment by s-desh** [comment]
> Yes exactly, that would be the idea. And having a `tokenized_sentence` where there is a 1:1 correspondence between token and POS.

Understood, will make the required cahnges

**Comment by s-desh** [comment]
@sg-wbi , I've made the required changes.

**Review by sg-wbi — APPROVED** [review]
Thank you for fixing this @s-desh ! Sorry it this took so long...
Nice to have this piece of history in the collection!

**Pull request merged**
