### PR TITLE
Closes #501 : BEAR Dataset

### LINKED ISSUE #501: Create dataset loader for BEAR
## Adding a Dataset
- **Name:** *BEAR*
- **Description:** *A Corpus of Biomedical Entities and Relations on Twitter*
- **Task:** *NER, RE*
- **Paper:** *[link to the dataset paper](https://arxiv.org/abs/2204.09952)*
- **Data:** *[link to the Github repository or current dataset location](https://www.ims.uni-stuttgart.de/en/research/resources/corpora/bioclaim/)*
- **License:** *CC BY-SA license: https://creativecommons.org/licenses/by-sa/4.0/*
- **Motivation:** *It reflects the patient's journey and their subjective perspective on the process of developing symptoms, being diagnosed and offered a treatment, being cured or learning to live with a medical condition*

### PR DESCRIPTION
**Pull request by karthikrangasai**
Closes #501 

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by hakunanatasha** [comment]
@karthikrangasai this looks good but I notice some of the relations are missing in the training data - is this a facet of the dataset (hence why the unit-tests may fail?)

**Comment by karthikrangasai** [comment]
Hello @hakunanatasha ,

When I ran the tests locally, all of them passed.
Let me check once again though to verify.

**Comment by karthikrangasai** [comment]
Hello @hakunanatasha ,

I ran the tests again and removed some unwanted lines of code. All the tests pass successfully.

**Comment by karthikrangasai** [comment]
@hakunanatasha , could you review the changes to the PR ?

**Review by mariosaenger — APPROVED** [review]

**Review by mariosaenger — APPROVED** [review]

**Pull request merged**
