### PR TITLE
Add implementation of ChemDisGene data set

### LINKED ISSUE #917: Add ChemDisGene data set
## Adding a Dataset
- **Name:** ChemDisGene
- **Description:** a collection of biomedical research abstracts annotated with mentions of chemical, disease and gene/gene-product entities, and pairwise relationships between those entities.
- **Task:** NER,NED,RE
- **Paper:** [https://aclanthology.org/2022.lrec-1.116/](https://aclanthology.org/2022.lrec-1.116/)
- **Data:** [https://github.com/chanzuckerberg/ChemDisGene](https://github.com/chanzuckerberg/ChemDisGene)
- **License:** CC0

### PR DESCRIPTION
**Pull request by mariosaenger**
Closes #917

### CODE REVIEW

**Review by leonweber — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution! It seems like the dataset statistics reported by the unit tests do not match those reported in the source paper (https://aclanthology.org/2022.lrec-1.116.pdf):

```
train
==========
id: 523
document_id: 523
passages: 1046
entities: 14248
normalized: 13686
events: 0
coreferences: 0
relations: 59414
```

Is this expected? Am I missing something?

**Comment by mariosaenger** [comment]
Thanks for checking the implementation. There are several aspects to keep in mind. First the dataset consists of a curated and a non-curated part. This implementation only concerns the former one. Second, the data set annotates relations only on abstract-level (using knowledge base identifiers). Following default practices in BigBio, I unrolled the document-level relations to mention-level. Note, however, the document-level annotations are available in the source schema. These aspects complicate a direct comparison of the numbers :-/

**Comment by leonweber** [comment]
Ah, thanks for pointing this out. Then let's merge this : )

**Review by leonweber — APPROVED** [review]
LGTM

**Pull request merged**
