### PR TITLE
Closes #137

### LINKED ISSUE #137: Create dataset loader for Mantra GSC
## Adding a Dataset
- **Name:** *Mantra GSC*
- **Description:** *We selected text units from different parallel corpora (Medline abstract titles, drug labels, biomedical patent claims) in English, French, German, Spanish, and Dutch. Three annotators per language independently annotated the biomedical concepts, based on a subset of the Unified Medical Language System and covering a wide range of semantic groups.*
- **Task:** *NER, NED*
- **Paper:** [*A multilingual gold-standard corpus for biomedical concept recognition: the Mantra GSC*](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4986661/)
- **Data:** *[https://files.ifi.uzh.ch/cl/mantra/gsc/GSC-v1.1.zip](https://files.ifi.uzh.ch/cl/mantra/gsc/GSC-v1.1.zip)*
- **License:** *[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)*
- **Motivation:** *This is a multilingual, parallel dataset (French, Spanish, Dutch, German, English)*

### PR DESCRIPTION
**Pull request by karthikrangasai**
Closes #137 

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by karthikrangasai** [comment]
Hello all,

The dataset is available in 5 languages (English, Spanish, Dutch, French, German) and 3 types (Patents, EMEA, Medline).

Currently, the only names possible are of the format `"mantra_gsc_<lang>_<type>_source"` or `"mantra_gsc_<lang>_<type>_bigbio_kb"`.

I need help with names like 
```
1. "mantra_gsc_source"
2. "mantra_gsc_bigbio_kb"
3. "mantra_gsc_<lang>_source" (All type of a single language)
4. "mantra_gsc_<lang>_bigbio_kb" (All type of a single language)
5. "mantra_gsc_<type>_source" (All languages of a single type)
6. "mantra_gsc_<type>_bigbio_kb" (All languages of a single type)
```

I am not sure how to make these work and thus would require some help. Thanks.

**Comment by hakunanatasha** [comment]
Hi @karthikrangasai just posted on the discord thread : )

For ease, I've also pinged here:

To run unit-tests, you can replace the argument to `subset_id` as follows:

`python -m tests.test_bigbio biodatasets/mantra_gsc/mantra_gsc.py --subset_id <name of the config ex: mantra_gsc_<lang>`

To test the dataloader, you can change the `name` argument to the config name:
```
from datasets import load_dataset
x = load_dataset("biodatasets/mantra_gsc/mantra_gsc.py", name="mantra_gsc_bigbio_kb")  # switch name to whatever config name you want
```

**Comment by karthikrangasai** [comment]
Thanks a lot. With `load_dataset` it was working, I wasn't sure about how to test it and you've cleared up my doubt.

My test is failing with the following error:
```
======================================================================
FAIL: runTest (__main__.TestDataLoader) [Check schema validity]
Run all tests that check:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthikrangasai/Open_Source/big_science/biomedical/tests/test_bigbio.py", line 115, in runTest
    self.test_schema(schema)
  File "/home/karthikrangasai/Open_Source/big_science/biomedical/tests/test_bigbio.py", line 544, in test_schema
    raise AssertionError(f"Required key '{non_empty_feature}' does not have any instances")
AssertionError: Required key 'normalized' does not have any instances

----------------------------------------------------------------------
```

What do I do here ? 
The dataset does not have any normalizations.

**Comment by galtay** [comment]
hi @karthikrangasai is the `normalized` issue solved? (seems to be) ... looks like the current issue is duplicate keys ... let us know if you need some help!

**Comment by karthikrangasai** [comment]
Hello @galtay ,

The issue is not resolved yet.

The following is the complete output of running tests:

```
$ python -m tests.test_bigbio biodatasets/mantra_gsc/mantra_gsc.py --subset_id mantra_gsc_fr_patents
INFO:__main__:args: Namespace(data_dir=None, path='biodatasets/mantra_gsc/mantra_gsc.py', schema=None, subset_id='mantra_gsc_fr_patents', use_auth_token=None)
INFO:__main__:self.PATH: biodatasets/mantra_gsc/mantra_gsc.py
INFO:__main__:self.SUBSET_ID: mantra_gsc_fr_patents
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: None
INFO:__main__:Checking for _SUPPORTED_TASKS ...
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.NAMED_ENTITY_RECOGNITION: 'NER'>, <Tasks.NAMED_ENTITY_DISAMBIGUATION: 'NED'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'KB'}
INFO:__main__:schemas_to_check: {'KB'}
INFO:__main__:Checking load_dataset with config name mantra_gsc_fr_patents_source
WARNING:datasets.builder:Reusing dataset mantra_gsc_dataset (/home/karthikrangasai/.cache/huggingface/datasets/mantra_gsc_dataset/mantra_gsc_fr_patents_source/1.0.0/c2319866fbfce5cf505036c8a02c656419dfefda7054267dad2ced2dd9f0be47)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.89it/s]
INFO:__main__:Checking load_dataset with config name mantra_gsc_fr_patents_bigbio_kb
WARNING:datasets.builder:Reusing dataset mantra_gsc_dataset (/home/karthikrangasai/.cache/huggingface/datasets/mantra_gsc_dataset/mantra_gsc_fr_patents_bigbio_kb/1.0.0/c2319866fbfce5cf505036c8a02c656419dfefda7054267dad2ced2dd9f0be47)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 113.48it/s]
INFO:__main__:Checking global ID uniqueness
INFO:__main__:Found 441 unique IDs
INFO:__main__:Gathering schema statistics
INFO:__main__:Gathering schema statistics
train
==========
id: 50
document_id: 50
passages: 50
entities: 341
normalized: 0
events: 0
coreferences: 0
relations: 0

INFO:__main__:Checking if referenced IDs are properly mapped
INFO:__main__:KB ONLY: Checking passage offsets
INFO:__main__:KB ONLY: Checking entity offsets
INFO:__main__:KB ONLY: Checking event offsets
INFO:__main__:KB ONLY: Checking coref offsets

======================================================================
FAIL: runTest (__main__.TestDataLoader) [Check schema validity]
Run all tests that check:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthikrangasai/Open_Source/big_science/biomedical/tests/test_bigbio.py", line 115, in runTest
    self.test_schema(schema)
  File "/home/karthikrangasai/Open_Source/big_science/biomedical/tests/test_bigbio.py", line 544, in test_schema
    raise AssertionError(f"Required key '{non_empty_feature}' does not have any instances")
AssertionError: Required key 'normalized' does not have any instances

----------------------------------------------------------------------
Ran 1 test in 1.177s

FAILED (failures=1)
```

**Comment by galtay** [comment]
it looks like there is a `CUI` field in the source data. when `SUPPORTED_TASKS` contains `NAMED_ENTITY_DISAMBIGUATION` the tests will look for the normalized fields to have links to a structured knowledge base for the entities. can these CUI values be used for this?

**Comment by karthikrangasai** [comment]
Hello @galtay ,

Sorry for the delayed response.
I am unsure how to use the CUI for normalized fields and also I am unsure if this dataset is for NED as well.
For now, I have marked the tasks as NER alone.

With this change, all the tests pass and  I checked for all subsets of the dataset.

**Comment by galtay** [comment]
Thanks @karthikrangasai . It looks to me like the CUI are references to the UMLS knowledge base. These can be included in the normalizations field like, 
```"normalized": [{"db_name": "UMLS", "db_id": <the CUI from the dataset>]}]```
you can see an example in the medmentions dataset https://github.com/bigscience-workshop/biomedical/blob/022163889bf24e99d9e43e1b2d37d8808dc43043/biodatasets/medmentions/medmentions.py#L228

**Comment by karthikrangasai** [comment]
Hello @galtay ,

Thanks for the guidance on how to solve the issue. I have updated the PR now with all the changes discussed.

**Review by galtay — APPROVED** [review]
thanks for the changes, looks good! :tada:

**Pull request merged**
