### PR TITLE
Closes #206

### LINKED ISSUE #206: Create dataset loader for AnEM
## Adding a Dataset
- **Name:** AnEM
- **Description:** *None provided*
- **Task:** NER
- **Paper:** https://aclanthology.org/W12-4304/
- **Data:** http://www.nactem.ac.uk/anatomy/
- **License:** CC BY-SA 3.0

### PR DESCRIPTION
**Pull request by s-desh**
Closes #206 
### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by sg-wbi** [comment]
@s-desh Thank you for your contribution! Could you please check a couple of things?

```python
        all_data = data_dir / "AnEM-1.0.4" / "standoff"
        split_dir = data_dir / "AnEM-1.0.4" / "test"
```
The dataset has a weird splitting of train/dev and test. However, it does seem to provide a `development` split. Could you please add it?

Secondly, and more importantly, when I run the tests I get these warnings:
```
WARNING:__main__:Found instances of 'coreferences' but there seems to be no task in 'SUPPORTED_TASKS' for them. Is 'SUPPORTED_TASKS' correct?
WARNING:__main__:Found instances of 'relations' but there seems to be no task in 'SUPPORTED_TASKS' for them. Is 'SUPPORTED_TASKS' correct?
WARNING:__main__:Found instances of 'coreferences' but there seems to be no task in 'SUPPORTED_TASKS' for them. Is 'SUPPORTED_TASKS' correct?
WARNING:__main__:Found instances of 'relations' but there seems to be no task in 'SUPPORTED_TASKS' for them. Is 'SUPPORTED_TASKS' correct?
```
This means that the example parsed with the `brat_parse_to_bigbio_kb` function contains `relation` and `coref` data. And this seems to be correct. If you run:
```bash
rg 'Arg' standoff/*.ann
standoff/PMC-2721088-sec-10.ann
5:R1	frag Arg1:T1 Arg2:T2	
23:R2	frag Arg1:T12 Arg2:T13	
42:R3	Part-of Arg1:T21 Arg2:T26	
```
and 
```bash
rg 'Equiv' standoff/*.ann
standoff/PMC-2701282-sec-04.ann
6:*	Equiv T3 T4
```
You see that there are relations (5:R1	frag Arg1:T1 Arg2:T5) and coreferences (6:*	Equiv T3 T4). Could you please fix the script accordingly and add the proper tasks (`constants.Tasks.COREFERENCE_RESOLUTION` and `constants.Tasks.RELATION_EXTRACTION`)

**Comment by s-desh** [comment]
Thank you for having a look at this PR @sg-wbi 
Yes, the dataset does have a wierd split of test/train/dev. In the current implementation, I'm using the train(300 docs)/test(200 docs) split provided in the test directory which covers all the data (500 documents). The development split provided is a subset of the already implemented train split (300 documents) as mentioned in the README - 
*PLEASE NOTE: the data in the development/ and test/ directories are
not separate: the development/ data is a split of the data in the
test/AnEM.train file.*
Shall I still go ahead and add the development split? (since it would be a duplicate/subset of train split)
The development split also contains a test/train subsplit. If I am to add the development split, should I combine the dev/train and dev/test subsplits?
Do let me know, I'll proceed accodingly.

I didn't add the other supported tasks earlier since the data was annotated only for an NER task. Will fix the script for other tasks as well.

**Comment by sg-wbi** [comment]
> I didn't add the other supported tasks earlier since the data was annotated only for an NER task. Will fix the script for other tasks as well.
Thank you!

**Comment by s-desh** [comment]
@sg-wbi, I've made the required changes.

**Review by sg-wbi — APPROVED** [review]
Great jon @s-desh! Let's close this! Thank you again for the contribution!

**Pull request merged**
