### PR TITLE
Closes #713

### LINKED ISSUE #713: bc7_litcovid returns None instances
## Describe the bug
`bc7_litcovid` generates instances with out a `text` field, e.g., `{'id': '34', 'document_id': '34219343', 'text': None, 'labels': ['Prevention']}`

## Steps to reproduce the bug
Iterate through the dataset as normal. 

## Expected results
`text` should have a value (since it has labels)

## Actual results
`text` is  `None` in several cases

### PR DESCRIPTION
**Pull request by shamikbose**
Passes all tests
No entries exist without "text" or "labels".
image

**NOTE:** This change applies to both "source" and "bigbio_text" schemas. If the "source" needs to remain unmodified, please let me know
Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

If the following information is NOT present in the issue, please populate:

- **Name:** *name of the dataset*
- **Description:** *short description of the dataset (or link to social media or blog post)*
- **Paper:** *link to the dataset paper if available*
- **Data:** *link to the online home of the dataset*

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by shamikbose** [comment]
Only missing entries were in the "validation" split. Missing entries are in rows 34, 386, 391, 690, 897, 1100, 1518, 1682, 2157, 2311, 2473

**Comment by phlobo** [comment]
Hi @shamikbose! We are currently in the process of going through open issues and PRs and merging them whenever possible. Since you have a number of open PRs (thank you for that!), I wanted to ask you if you could possibly update them to the current [contribution guide ](https://github.com/bigscience-workshop/biomedical/blob/main/CONTRIBUTING.md), i.e., making them compatible with the HF Hub.

If you don't have bandwidth for this, me and other maintainers would try to amend your PR by making the required changes ourselves, ideally still giving due credit to your contribution while doing that.

Please let me know what you think!

**Comment by shamikbose** [comment]
@phlobo I'm happy to take a look at the open PRs from my end on the weekend

**Comment by phlobo** [comment]
@shamikbose Thank you for your contribution!

I encountered various conflicts when trying to rebase this branch with the main repo, therefore I had to open a new PR with your changes: #949

**Pull request closed without merging**
