### PR TITLE
Closes #217

### LINKED ISSUE #217: Create dataset loader for LLL
## Adding a Dataset
- **Name:** LLL
- **Description:** *None provided*
- **Task:** RE,NER
- **Paper:** http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=4B3F165F09189F5487A59C6E0C19C855?doi=10.1.1.96.5066&rep=rep1&type=pdf
- **Data:** http://genome.jouy.inra.fr/texte/LLLchallenge/
- **License:** ?

### PR DESCRIPTION
**Pull request by nomisto**
Closes #217

Task of dataset is Relation Extraction, however it was part of a challenge where the correct answers to the test set were never released. Since `data["test"]["relations"]` is thus empty for the testset the test fails with:

```bash
ERROR: runTest (__main__.TestDataLoader)
Run all tests that check:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ottsi\biomedical\tests\test_bigbio.py", line 116, in runTest
    self.test_schema(schema)
  File "C:\Users\ottsi\biomedical\tests\test_bigbio.py", line 518, in test_schema
    self.assertTrue(self._check_subkey(example[key][0], attrs))
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 1.195s

FAILED (errors=1)
```

Edit: On second thought I think this might be a bug in the test-script, since it is assumed that a required subkey has to have elements in it. F.e. also in NER there could be documents without any entities at all in them.

### CODE REVIEW

**Comment by leonweber** [comment]
Hey @nomisto, this is definitely a bug in the test script. We'll fix it and then review this PR.

**Comment by hakunanatasha** [comment]
@nomisto as you get closer to submitting, can you change the PR title to be closes #332?

**Comment by nomisto** [comment]
@hakunanatasha Sure, sorry, read the PR template too quickly!

**Comment by leonweber** [comment]
@nomisto Tests should work now with #336 . Can you please try and report the results?

**Comment by nomisto** [comment]
@leonweber Tests work very well! The result `AssertionError: Required key 'relations' does not have any instances` seems expected (See output below, collapsed).

<details>
<summary>Output of test</summary>

```bash
INFO:__main__:args: Namespace(data_dir=None, path='biodatasets/lll/lll.py', schema=None, subset_id=None, use_auth_token=None)
INFO:__main__:self.PATH: biodatasets/lll/lll.py
INFO:__main__:self.SUBSET_ID: lll
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: None
INFO:__main__:Checking for _SUPPORTED_TASKS ...
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.RELATION_EXTRACTION: 'RE'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'KB'}
INFO:__main__:schemas_to_check: {'KB'}
INFO:__main__:Checking load_dataset with config name lll_source
WARNING:datasets.builder:Reusing dataset lll_dataset (C:\Users\Simon\.cache\huggingface\datasets\lll_dataset\lll_source\1.0.0\bb4d25270803e7e424ea31957fdee7a1e42d114de738e98d620fbafbf2d2f899)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 499.29it/s]
INFO:__main__:Checking load_dataset with config name lll_bigbio_kb
Downloading and preparing dataset lll_dataset/lll_bigbio_kb to C:\Users\Simon\.cache\huggingface\datasets\lll_dataset\lll_bigbio_kb\1.0.0\bb4d25270803e7e424ea31957fdee7a1e42d114de738e98d620fbafbf2d2f899...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 2985.27it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 750.01it/s] 
Dataset lll_dataset downloaded and prepared to C:\Users\Simon\.cache\huggingface\datasets\lll_dataset\lll_bigbio_kb\1.0.0\bb4d25270803e7e424ea31957fdee7a1e42d114de738e98d620fbafbf2d2f899. Subsequent calls will reuse this data.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 95.19it/s] 
INFO:__main__:Checking global ID uniqueness
INFO:__main__:Found 2152 unique IDs
INFO:__main__:Gathering schema statistics
INFO:__main__:Gathering schema statistics
train
==========
id: 77
document_id: 77
passages: 77
entities: 1996
normalized: 0
events: 0
coreferences: 0
relations: 164

test
==========
id: 87
document_id: 87
passages: 87
entities: 1978
normalized: 0
events: 0
coreferences: 0
relations: 0

INFO:__main__:Checking if referenced IDs are properly mapped
INFO:__main__:KB ONLY: Checking passage offsets
INFO:__main__:KB ONLY: Checking entity offsets
INFO:__main__:KB ONLY: Checking event offsets
INFO:__main__:KB ONLY: Checking coref offsets

======================================================================
FAIL: runTest (__main__.TestDataLoader) [Check schema validity]
Run all tests that check:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Simon\biomedical\tests\test_bigbio.py", line 115, in runTest
    self.test_schema(schema)
  File "C:\Users\Simon\biomedical\tests\test_bigbio.py", line 513, in test_schema
    raise AssertionError(f"Required key '{non_empty_feature}' does not have any instances")
AssertionError: Required key 'relations' does not have any instances

----------------------------------------------------------------------
Ran 1 test in 1.540s

FAILED (failures=1)
```

</details>

Sorry, I've got another issue: The offsets in `source` are different from `bigbio`, since the original data sets the stopOffset to the exact index of the last char. F.e. for the sentence 'In vivo studies ..." the offsets for "In" would be [0,1]. I changed that so now its `start,stop` for source and `start, stop + 1` for bigbio. Is this alright or should I change the offsets also for the `source` config?

**Comment by hakunanatasha** [comment]
@nomisto will get back to you on this ASAP

**Comment by hakunanatasha** [comment]
@nomisto @jason-fries yes; the change is fine - let me know when it's ready for review. Please make note, in the script, that you have done this for future reference.

**Comment by nomisto** [comment]
Thanks, I've included a note in the script.

**Comment by hakunanatasha** [comment]
@nomisto is there a particular way you're running the scripts? I'm getting the following error:
```
FAIL: runTest (__main__.TestDataLoader) [Check schema validity]
Run all tests that check:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/natasha/Projects/hfbiomed/biomedical/tests/test_bigbio.py", line 115, in runTest
    self.test_schema(schema)
  File "/home/natasha/Projects/hfbiomed/biomedical/tests/test_bigbio.py", line 544, in test_schema
    raise AssertionError(f"Required key '{non_empty_feature}' does not have any instances")
AssertionError: Required key 'relations' does not have any instances

----------------------------------------------------------------------
Ran 1 test in 3.584s
```

It's possible this is happening because a split is missing examples in a key (i.e. "test" is missing any populated relations). If so, I'm working on an adaptation to the unit tests with #398 that should be merged shortly. If not, let me know.

**Review by hakunanatasha — CHANGES_REQUESTED** [review]
please pass unit-tests

**Comment by nomisto** [comment]
Hi @hakunanatasha , Sorry I did not recieve notifications for this. This dataset was part of a challenge where the correct answers to the test set were never released. Thus data["test"]["relations"] is empty for the "test" split.

I think @leonweber made fixes so that it runs all tests, but still prints `AssertionError: Required key 'relations' does not have any instances`. [see comment](https://github.com/bigscience-workshop/biomedical/pull/332#issuecomment-1089228007)

**Comment by galtay** [comment]
I updated the offsets for the source schema and noted the missing relationships in the test set. Going to merge now.

**Review by galtay — APPROVED** [review]

**Pull request merged**
