### PR TITLE
Closes #55

### LINKED ISSUE #55: Create a dataset loader for MEDIQA 2019 RQE
From https://github.com/abachaa/MEDIQA2019/tree/master/MEDIQA_Task2_RQE

### PR DESCRIPTION
**Pull request by SamuelCahyawijaya**
Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

If the following information is NOT present in the issue, please populate:

- **Name:** MEDIQA 2019 RQE
- **Description:** https://sites.google.com/view/mediqa2019
- **Paper:** https://aclanthology.org/W19-5039/
- **Data:** https://github.com/abachaa/MEDIQA2019

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.

### CODE REVIEW

**Review by hakunanatasha — CHANGES_REQUESTED** [review]
Hi @SamuelCahyawijaya 

I can accept this PR as it passes tests and looks good, but can you please remove the 2 jpgs from the PR before I do so? I don't see why they need to be committed.

**Comment by SamuelCahyawijaya** [comment]
Hi @hakunanatasha, I think this is because I make another commit after my last PR on the README, and I forgot to push it. I have deleted these two image files now.

**Review by ruisi-su — CHANGES_REQUESTED** [review]
Hi @SamuelCahyawijaya, thanks for the quick turnaround! I just checked the latest commit, this PR seems to carry the other PR you raised for mediqa_qa. Could you please remove the overlap from this PR? Thanks again!

**Comment by SamuelCahyawijaya** [comment]
@ruisi-su : Oh, my bad. I commited the wrong file to the wrong branch. I deleted the mediqa_qa.py from this branch.

**Comment by hakunanatasha** [comment]
Hi @SamuelCahyawijaya; I think you actually `git rm` the file as opposed to unstaging the commit; I'm going to merge this, but I believe it will accidentally delete the two images on the main branch. 

It's not an issue, since the PRs pass and I'll just manually add these later, but in the future please just omit the commit as opposed to removing the images (my fault on wording :P). Great job on the PR.

**Review by hakunanatasha — APPROVED** [review]

**Comment by SamuelCahyawijaya** [comment]
@hakunanatasha : I see, thanks for the advice and help in fixing the issue. Sure, I will do that next time!

**Pull request merged**
